version: "3.9"
services:

  # MySQL
  db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      ports: 
          - 3306:3306
      environment:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: todo-list
          MYSQL_USER: user
          MYSQL_PASSWORD: password

  # [Optional] adminer
  adminer:
      image: adminer
      restart: always
      ports:
          - 8080:8080

  # Server
  server:
    restart: always
    build: Server/
    command: go run server.go
    ports:
    - "1323:1323"
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: todo-list
      SERVER_HOST: localhost
      SERVER_PORT: 1323
    depends_on:
     - db
  
  # Client
  client:
    restart: always
    build: Client/
    environment:
      SERVER_HOST: localhost
      SERVER_PORT: 1323
    network_mode: host
    depends_on:
     - server
    stdin_open: true 
    tty: true
    

